/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

/**
 *
 * @author burak
 */
public class DealOrNoDeal extends javax.swing.JFrame {

    /**
     * Creates new form DealOrNoDeal
     */
    public DealOrNoDeal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        oneLira = new javax.swing.JButton();
        fiveLira = new javax.swing.JButton();
        tenLira = new javax.swing.JButton();
        fifteenLira = new javax.swing.JButton();
        twentyfiveLira = new javax.swing.JButton();
        fiftyLira = new javax.swing.JButton();
        seventyfiveLira = new javax.swing.JButton();
        onehundredLira = new javax.swing.JButton();
        twohundredLira = new javax.swing.JButton();
        threehundredLira = new javax.swing.JButton();
        fourhundredLira = new javax.swing.JButton();
        fivehundredLira = new javax.swing.JButton();
        sevenhundredfiftyLira = new javax.swing.JButton();
        onekLira = new javax.swing.JButton();
        fivekLira = new javax.swing.JButton();
        tenkLira = new javax.swing.JButton();
        twentyfivekLira = new javax.swing.JButton();
        fiftykLira = new javax.swing.JButton();
        seventyfivekLira = new javax.swing.JButton();
        onehundredkLira = new javax.swing.JButton();
        twohundredkLira = new javax.swing.JButton();
        threehundredkLira = new javax.swing.JButton();
        fourhundredkLira = new javax.swing.JButton();
        fivehundredkLira = new javax.swing.JButton();
        sevenhundredfiftykLira = new javax.swing.JButton();
        onemLira = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        caseThree = new javax.swing.JButton();
        caseOne = new javax.swing.JButton();
        caseTwo = new javax.swing.JButton();
        caseFour = new javax.swing.JButton();
        caseFive = new javax.swing.JButton();
        caseEleven = new javax.swing.JButton();
        caseTwelve = new javax.swing.JButton();
        caseThirteen = new javax.swing.JButton();
        caseFourteen = new javax.swing.JButton();
        caseFifteen = new javax.swing.JButton();
        caseSeventeen = new javax.swing.JButton();
        caseEighteen = new javax.swing.JButton();
        caseNineteen = new javax.swing.JButton();
        caseTwenty = new javax.swing.JButton();
        caseTwentyOne = new javax.swing.JButton();
        caseSix = new javax.swing.JButton();
        caseSeven = new javax.swing.JButton();
        caseEight = new javax.swing.JButton();
        caseNine = new javax.swing.JButton();
        caseTen = new javax.swing.JButton();
        caseTwentyTwo = new javax.swing.JButton();
        caseTwentyThree = new javax.swing.JButton();
        caseTwentyFour = new javax.swing.JButton();
        caseTwentyFive = new javax.swing.JButton();
        caseTwentySix = new javax.swing.JButton();
        caseSixteen = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        newGame = new javax.swing.JMenuItem();
        exitGame = new javax.swing.JMenuItem();
        offers = new javax.swing.JMenu();
        about = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Deal Or No Deal");

        oneLira.setText("1 TL");

        fiveLira.setText("5 TL");
        fiveLira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveLiraActionPerformed(evt);
            }
        });

        tenLira.setText("10 TL");

        fifteenLira.setText("15 TL");

        twentyfiveLira.setText("25 TL");

        fiftyLira.setText("50 TL");

        seventyfiveLira.setText("75 TL");

        onehundredLira.setText("100 TL");

        twohundredLira.setText("200 TL");

        threehundredLira.setText("300 TL");

        fourhundredLira.setText("400 TL");

        fivehundredLira.setText("500 TL");

        sevenhundredfiftyLira.setText("750 TL");

        onekLira.setText("1,000 TL");

        fivekLira.setText("5,000 TL");

        tenkLira.setText("10,000 TL");

        twentyfivekLira.setText("25,000 TL");

        fiftykLira.setText("50,000 TL");

        seventyfivekLira.setText("75,000 TL");

        onehundredkLira.setText("100,000 TL");

        twohundredkLira.setText("200,000 TL");

        threehundredkLira.setText("300,000 TL");

        fourhundredkLira.setText("400,000 TL");

        fivehundredkLira.setText("500,000 TL");

        sevenhundredfiftykLira.setText("750,000 TL");

        onemLira.setText("1,000,000 TL");
        onemLira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onemLiraActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        label.setText("CHOOSE YOUR CASE");

        caseThree.setBackground(java.awt.Color.blue);
        caseThree.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseThree.setForeground(new java.awt.Color(0, 102, 255));
        caseThree.setText("3");
        caseThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseThreeMouseClicked(evt);
            }
        });

        caseOne.setBackground(java.awt.Color.blue);
        caseOne.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseOne.setForeground(new java.awt.Color(0, 102, 255));
        caseOne.setText("1");
        caseOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseOneMouseClicked(evt);
            }
        });

        caseTwo.setBackground(java.awt.Color.blue);
        caseTwo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTwo.setForeground(new java.awt.Color(0, 102, 255));
        caseTwo.setText("2");
        caseTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTwoMouseClicked(evt);
            }
        });

        caseFour.setBackground(java.awt.Color.blue);
        caseFour.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseFour.setForeground(new java.awt.Color(0, 102, 255));
        caseFour.setText("4");
        caseFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseFourMouseClicked(evt);
            }
        });

        caseFive.setBackground(java.awt.Color.blue);
        caseFive.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseFive.setForeground(new java.awt.Color(0, 102, 255));
        caseFive.setText("5");
        caseFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseFiveMouseClicked(evt);
            }
        });

        caseEleven.setBackground(java.awt.Color.blue);
        caseEleven.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseEleven.setForeground(new java.awt.Color(0, 102, 255));
        caseEleven.setText("11");
        caseEleven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseElevenMouseClicked(evt);
            }
        });

        caseTwelve.setBackground(java.awt.Color.blue);
        caseTwelve.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTwelve.setForeground(new java.awt.Color(0, 102, 255));
        caseTwelve.setText("12");
        caseTwelve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTwelveMouseClicked(evt);
            }
        });

        caseThirteen.setBackground(java.awt.Color.blue);
        caseThirteen.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseThirteen.setForeground(new java.awt.Color(0, 102, 255));
        caseThirteen.setText("13");
        caseThirteen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseThirteenMouseClicked(evt);
            }
        });

        caseFourteen.setBackground(java.awt.Color.blue);
        caseFourteen.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseFourteen.setForeground(new java.awt.Color(0, 102, 255));
        caseFourteen.setText("14");
        caseFourteen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseFourteenMouseClicked(evt);
            }
        });

        caseFifteen.setBackground(java.awt.Color.blue);
        caseFifteen.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseFifteen.setForeground(new java.awt.Color(0, 102, 255));
        caseFifteen.setText("15");
        caseFifteen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseFifteenMouseClicked(evt);
            }
        });

        caseSeventeen.setBackground(java.awt.Color.blue);
        caseSeventeen.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseSeventeen.setForeground(new java.awt.Color(0, 102, 255));
        caseSeventeen.setText("17");
        caseSeventeen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseSeventeenMouseClicked(evt);
            }
        });

        caseEighteen.setBackground(java.awt.Color.blue);
        caseEighteen.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseEighteen.setForeground(new java.awt.Color(0, 102, 255));
        caseEighteen.setText("18");
        caseEighteen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseEighteenMouseClicked(evt);
            }
        });

        caseNineteen.setBackground(java.awt.Color.blue);
        caseNineteen.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseNineteen.setForeground(new java.awt.Color(0, 102, 255));
        caseNineteen.setText("19");
        caseNineteen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseNineteenMouseClicked(evt);
            }
        });

        caseTwenty.setBackground(java.awt.Color.blue);
        caseTwenty.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTwenty.setForeground(new java.awt.Color(0, 102, 255));
        caseTwenty.setText("20");
        caseTwenty.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTwentyMouseClicked(evt);
            }
        });

        caseTwentyOne.setBackground(java.awt.Color.blue);
        caseTwentyOne.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTwentyOne.setForeground(new java.awt.Color(0, 102, 255));
        caseTwentyOne.setText("21");
        caseTwentyOne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTwentyOneMouseClicked(evt);
            }
        });

        caseSix.setBackground(java.awt.Color.blue);
        caseSix.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseSix.setForeground(new java.awt.Color(0, 102, 255));
        caseSix.setText("6");
        caseSix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseSixMouseClicked(evt);
            }
        });

        caseSeven.setBackground(java.awt.Color.blue);
        caseSeven.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseSeven.setForeground(new java.awt.Color(0, 102, 255));
        caseSeven.setText("7");
        caseSeven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseSevenMouseClicked(evt);
            }
        });

        caseEight.setBackground(java.awt.Color.blue);
        caseEight.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseEight.setForeground(new java.awt.Color(0, 102, 255));
        caseEight.setText("8");
        caseEight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseEightMouseClicked(evt);
            }
        });

        caseNine.setBackground(java.awt.Color.blue);
        caseNine.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseNine.setForeground(new java.awt.Color(0, 102, 255));
        caseNine.setText("9");
        caseNine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseNineMouseClicked(evt);
            }
        });

        caseTen.setBackground(java.awt.Color.blue);
        caseTen.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTen.setForeground(new java.awt.Color(0, 102, 255));
        caseTen.setText("10");
        caseTen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTenMouseClicked(evt);
            }
        });

        caseTwentyTwo.setBackground(java.awt.Color.blue);
        caseTwentyTwo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTwentyTwo.setForeground(new java.awt.Color(0, 102, 255));
        caseTwentyTwo.setText("22");
        caseTwentyTwo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTwentyTwoMouseClicked(evt);
            }
        });

        caseTwentyThree.setBackground(java.awt.Color.blue);
        caseTwentyThree.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTwentyThree.setForeground(new java.awt.Color(0, 102, 255));
        caseTwentyThree.setText("23");
        caseTwentyThree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTwentyThreeMouseClicked(evt);
            }
        });

        caseTwentyFour.setBackground(java.awt.Color.blue);
        caseTwentyFour.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTwentyFour.setForeground(new java.awt.Color(0, 102, 255));
        caseTwentyFour.setText("24");
        caseTwentyFour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTwentyFourMouseClicked(evt);
            }
        });

        caseTwentyFive.setBackground(java.awt.Color.blue);
        caseTwentyFive.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTwentyFive.setForeground(new java.awt.Color(0, 102, 255));
        caseTwentyFive.setText("25");
        caseTwentyFive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTwentyFiveMouseClicked(evt);
            }
        });

        caseTwentySix.setBackground(java.awt.Color.blue);
        caseTwentySix.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseTwentySix.setForeground(new java.awt.Color(0, 102, 255));
        caseTwentySix.setText("26");
        caseTwentySix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseTwentySixMouseClicked(evt);
            }
        });

        caseSixteen.setBackground(java.awt.Color.blue);
        caseSixteen.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        caseSixteen.setForeground(new java.awt.Color(0, 102, 255));
        caseSixteen.setText("16");
        caseSixteen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caseSixteenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(caseSix, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caseSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caseEight, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caseNine, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caseTen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(caseOne, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caseTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caseThree, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caseFour, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(caseFive, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(caseEleven, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caseTwelve, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caseThirteen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caseFourteen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caseFifteen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(caseSixteen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(caseSeventeen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseEighteen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseNineteen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseTwenty, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseTwentyOne, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(caseTwentyTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseTwentyThree, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseTwentyFour, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseTwentyFive, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caseTwentySix, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseThree, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseOne, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseFour, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseFive, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseEight, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseSix, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseSeven, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseNine, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseTen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseThirteen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseEleven, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseTwelve, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseFourteen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseFifteen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseSixteen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseNineteen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseSeventeen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseEighteen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseTwenty, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseTwentyOne, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caseTwentyFour, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseTwentyTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseTwentyThree, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseTwentyFive, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caseTwentySix, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        file.setText("File");
        file.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fileMouseEntered(evt);
            }
        });

        newGame.setText("New Game");
        newGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newGameMouseClicked(evt);
            }
        });
        newGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameActionPerformed(evt);
            }
        });
        file.add(newGame);

        exitGame.setText("Exit Game");
        exitGame.setToolTipText("");
        exitGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitGameMouseClicked(evt);
            }
        });
        file.add(exitGame);

        jMenuBar1.add(file);

        offers.setText("Past Offers");
        offers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                offersMouseClicked(evt);
            }
        });
        jMenuBar1.add(offers);

        about.setText("About");
        about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMouseClicked(evt);
            }
        });
        jMenuBar1.add(about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fourhundredLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(twohundredLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(threehundredLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onehundredLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seventyfiveLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fiftyLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twentyfiveLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fifteenLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fiveLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(oneLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sevenhundredfiftyLira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fivehundredLira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sevenhundredfiftykLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onemLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fivehundredkLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fourhundredkLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(threehundredkLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twohundredkLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onehundredkLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(seventyfivekLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fiftykLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(twentyfivekLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tenkLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fivekLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(onekLira, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oneLira)
                            .addComponent(onekLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiveLira)
                            .addComponent(fivekLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tenLira)
                            .addComponent(tenkLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fifteenLira)
                            .addComponent(twentyfivekLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twentyfiveLira)
                            .addComponent(fiftykLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fiftyLira)
                            .addComponent(seventyfivekLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seventyfiveLira)
                            .addComponent(onehundredkLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(onehundredLira)
                            .addComponent(twohundredkLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(twohundredLira)
                            .addComponent(threehundredkLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(threehundredLira)
                            .addComponent(fourhundredkLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fourhundredLira)
                            .addComponent(fivehundredkLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fivehundredLira)
                            .addComponent(sevenhundredfiftykLira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sevenhundredfiftyLira)
                            .addComponent(onemLira))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void aboutMouseClicked(java.awt.event.MouseEvent evt) {                                   
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Created by Burak Çeltik\ngithub.com/fazlaejderhasiolanvarmi");
    }                                  

    private void fileMouseEntered(java.awt.event.MouseEvent evt) {                                  
        // sil
    }                                 

    private void offersMouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
    }                                   

    private void fiveLiraActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // sil
    }                                        

    private void onemLiraActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // sil
    }                                        

    private void newGameActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // sil
    }                                       

    private void newGameMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void exitGameMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void caseOneMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void caseTwoMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void caseThreeMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void caseFourMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void caseFiveMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void caseSixMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void caseSevenMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void caseEightMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void caseNineMouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void caseTenMouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void caseElevenMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void caseTwelveMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void caseThirteenMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void caseFourteenMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void caseFifteenMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void caseSixteenMouseClicked(java.awt.event.MouseEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void caseSeventeenMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void caseEighteenMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void caseNineteenMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void caseTwentyMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void caseTwentyOneMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void caseTwentyTwoMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void caseTwentyThreeMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void caseTwentyFourMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void caseTwentyFiveMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void caseTwentySixMouseClicked(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DealOrNoDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DealOrNoDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DealOrNoDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DealOrNoDeal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DealOrNoDeal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JMenu about;
    private javax.swing.JButton caseEight;
    private javax.swing.JButton caseEighteen;
    private javax.swing.JButton caseEleven;
    private javax.swing.JButton caseFifteen;
    private javax.swing.JButton caseFive;
    private javax.swing.JButton caseFour;
    private javax.swing.JButton caseFourteen;
    private javax.swing.JButton caseNine;
    private javax.swing.JButton caseNineteen;
    private javax.swing.JButton caseOne;
    private javax.swing.JButton caseSeven;
    private javax.swing.JButton caseSeventeen;
    private javax.swing.JButton caseSix;
    private javax.swing.JButton caseSixteen;
    private javax.swing.JButton caseTen;
    private javax.swing.JButton caseThirteen;
    private javax.swing.JButton caseThree;
    private javax.swing.JButton caseTwelve;
    private javax.swing.JButton caseTwenty;
    private javax.swing.JButton caseTwentyFive;
    private javax.swing.JButton caseTwentyFour;
    private javax.swing.JButton caseTwentyOne;
    private javax.swing.JButton caseTwentySix;
    private javax.swing.JButton caseTwentyThree;
    private javax.swing.JButton caseTwentyTwo;
    private javax.swing.JButton caseTwo;
    private javax.swing.JMenuItem exitGame;
    private javax.swing.JButton fifteenLira;
    private javax.swing.JButton fiftyLira;
    private javax.swing.JButton fiftykLira;
    private javax.swing.JMenu file;
    private javax.swing.JButton fiveLira;
    private javax.swing.JButton fivehundredLira;
    private javax.swing.JButton fivehundredkLira;
    private javax.swing.JButton fivekLira;
    private javax.swing.JButton fourhundredLira;
    private javax.swing.JButton fourhundredkLira;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JMenuItem newGame;
    private javax.swing.JMenu offers;
    private javax.swing.JButton oneLira;
    private javax.swing.JButton onehundredLira;
    private javax.swing.JButton onehundredkLira;
    private javax.swing.JButton onekLira;
    private javax.swing.JButton onemLira;
    private javax.swing.JButton sevenhundredfiftyLira;
    private javax.swing.JButton sevenhundredfiftykLira;
    private javax.swing.JButton seventyfiveLira;
    private javax.swing.JButton seventyfivekLira;
    private javax.swing.JButton tenLira;
    private javax.swing.JButton tenkLira;
    private javax.swing.JButton threehundredLira;
    private javax.swing.JButton threehundredkLira;
    private javax.swing.JButton twentyfiveLira;
    private javax.swing.JButton twentyfivekLira;
    private javax.swing.JButton twohundredLira;
    private javax.swing.JButton twohundredkLira;
    // End of variables declaration                   
}
